# Application configuration.  This should be changed to match the account
# settings as defined in your OnTime account.
#

account_name: "ad-juster"
excluded_statuses: ["On Hold", "Waiting", "Closed"]
excluded_workflow_steps: ["Completed", "Fixed", "Ready For Testing", "Rejected"]
