# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
excluded_statuses: ["On Hold", "Waiting", "Closed"]
excluded_workflow_steps: ["Completed", "Fixed", "Ready For Testing", "Rejected"]
